GET http://localhost:3080/

###

DELETE http://localhost:3080/9

###

DELETE http://localhost:3080/5

###

DELETE http://localhost:3080/2


{
    "title": "Minecraft",
    "studio": "Mojang",
    "price": 150
}